version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - 3003:5432
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - ./src/config/schemas/dev.sql:/docker-entrypoint-initdb.d/dev.sql