version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      -3002:5432
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - ./src/config/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql